install! 'cocoapods', :disable_input_output_paths => true
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '16.0'

target 'MonriAndroidIosExample' do
  config = use_native_modules!

  use_react_native!(path: '../node_modules/react-native')

  pod 'react-native-monri-android-ios', :path => '../..'

  post_install do |installer|
    # 1) Ensure every pod target uses at least iOS 13.0
    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      end
    end
  end
end